# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Society of Business Intelligence"

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Simple Jekyll theme to host internal/external events happening in and around your area. Free free to contribute or fork the repo.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ugasbi.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: David Boyne
twitter_username: ugasbi
company_name: UGA SBI

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

cover: http://ugasbi.weebly.com/uploads/8/0/8/1/80816214/published/1474890886.png?1486223719

exclude:
    - .explorer
    - .sass-cache
    - _site

timezone: America/New_York

sass:
    style: compressed